{% set name = "settings-doc" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/settings_doc-{{ version }}.tar.gz
  sha256: f15535c42f4330a454306ddebc79dd5c0acf45b1af7e87ab0cabc0b10e340148

build:
  entry_points:
    - settings-doc = settings_doc.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - jinja2 >=3.0.2,<4.0.0
    - pydantic >=2.3.0,<3.0.0
    - pydantic-settings >=2.0.3,<3.0.0
    - click >=8.0.0,<9.0.0

test:
  imports:
    - settings_doc
  commands:
    - pip check
    - settings-doc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/radeklat/settings-doc
  summary: A command line tool for generating Markdown documentation and .env files from pydantic BaseSettings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
